### ISSUE TITLE
[Request] Can I use a custom title for the screenshot to be generated?

### ISSUE THREAD

**Issue by lamualfa** [ericliu-el/coldcode#1]
### Problem

Sometimes if I want to ask a question in the question and answer forum, I have a little objection if I have to display the real name of the file or project I'm working on. So from that, can I enter a custom title for each screenshot that will be generated?

**Comment by ericliu-el** [comment]
Hi @lamualfa Thank you for your advice. It's a good idea of editing custom title.

I may take a look and find a way to add it in the future.

**Comment by tharwaatt** [comment]
Where can I find the screenshot after saving ?

**Comment by ericliu-el** [comment]
> Where can I find the screenshot after saving ?

Hi @Tharwat-07 ,

You can:

1. "Download" it, and a window will pop up for you to choose where to store the screenshot. 
2. "Copy" it, which will copy the screenshot to your clipboard, then you can paste it somewhere as you need.

**Comment by ericliu-el** [comment]
Hi @lamualfa  

I have released a new version which supports the custom title feature. 
Feel free to check it out.

Happy coding!

**Comment by lamualfa** [comment]
Great! Thank you very much.
