### ISSUE TITLE
Useing coldcode will "copy on selection",and when close coldcode it still is.

### ISSUE THREAD

**Issue by Unitary-orz** [ericliu-el/coldcode#3]
l like this extension，but this bug bother me badly.Only quit VScode，"copy on selection" was closed.

**Comment by Unitary-orz** [comment]
this fix of process，will help you
[After using PolaCode, selecting any text copies it · Issue #107 · octref/polacode](https://github.com/octref/polacode/issues/107) 
[Fix #107 · octref/polacode@d80aa44](https://github.com/octref/polacode/commit/d80aa44cc14839370d6898b995176af8a9dc6a13)

**Comment by ericliu-el** [comment]
@Unitary-orz 

Thank you for using coldcode.

It's fixed from v1.1.1

Happy coding.
