### ISSUE TITLE
[REQUEST] Add possibility to export as svg 

### ISSUE THREAD

**Issue by TheWCKD** [ericliu-el/coldcode#8]
Hello,

First and foremost, amazing extension, I must admit out of every plugin I have tried, yours is definitely the most customizable and complex one! 

However, I would like to ask you if you'd consider adding an option to export the image as an svg so that during scaling it won't pixelate. Thanks!

**Comment by ericliu-el** [comment]
Hi @TheWCKD, I think it's a great idea. I will take a look and see how to make it work well.

Thank you.

**Comment by TheWCKD** [comment]
> Hi @TheWCKD, I think it's a great idea. I will take a look and see how to make it work well.
> 
> Thank you.

Thank you so much, I am really looking forward to seeing it!

**Comment by ericliu-el** [comment]
Hi @TheWCKD,

I have added the SVG support and release the new version 1.2.0.  Feel free to have a try. 

The underlying library exporting SVG may not work 100% perfectly in some edge cases, but it should work well most time.

Thanks again for your suggestion.

**Comment by TheWCKD** [comment]
> Hi @TheWCKD,
> 
> I have added the SVG support and release the new version 1.2.0.  Feel free to have a try. 
> 
> The underlying library exporting SVG may not work 100% perfectly in some edge cases, but it should work well most time.
> 
> Thanks again for your suggestion.

Thank you so much! I will take a look as soon as possible and give you some feedback! Thanks again!

**Comment by TheWCKD** [comment]
It works perfect, as expected! Thanks for your quick replies and implementation. And keep an eye on [Flutterly YouTube Channel](https://youtube.com/c/flutterly), I'll showcase your plugin as soon as I finish one of my tutorial series! Thanks again!
